In [1]:
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
df_casasFULL = pd.read_csv(r'csvRS/casas-pro.csv')

In [3]:
#Se limpian los valores de precio y mets y se convierte a flotantes
df_casasFULL['precio'] = df_casasFULL['precio'].replace('[^\d.]', '', regex=True).astype(float)
df_casasFULL['mets'] = df_casasFULL['mets'].replace('[^\d.]', '', regex=True).astype(float)

In [4]:
df_casasFULL = df_casasFULL[df_casasFULL['web-scraper-start-url'].str.contains("campanario", na=False, case=False)]
df_casasFULL.reset_index(drop=True, inplace=True)

In [5]:
df_casasFULL.loc[:,['titulo','precio','mets']]

titulo      precio    mets
0            El Campanario, Jardín Colindante con Lago  26000000.0  1250.0
1    Preciosa Residencia de Autor en El Campanario,...  13800000.0   814.0
2                 Casa - Fraccionamiento El Campanario  19800000.0  1277.0
3    Lujosa Casa en El Campanario Lista Para Estren...  19990000.0   700.0
4                       Casa en Venta en El Campanario  30000000.0  1250.0
..                                                 ...         ...     ...
413  Listo para Abril 2022 casa en El Campanario de...  40000000.0   900.0
414        RESIDENCIA EN PREVENTA CAMPANARIO QUERETARO  18950000.0   752.0
415  El Campanario casa muy amplia de 4 recamaras! JGJ  19990000.0   500.0
416   El Campanario casa a estrenar de 4 recamaras RCS  19990000.0   500.0
417  CASA EN VENTA EN EL CAMPANARIO, 4 REC., 5.5 BA...  19750000.0   630.0

[418 rows x 3 columns]

In [6]:
#Se obtienen 334 casas las cuales corresponden al 80%, estos seran usados para Entrenamiento
df_casasCamp80p = df_casasFULL.loc[0:333,['titulo','precio','mets']]

In [7]:
#Se obtienen 84 casas las cuales corresponden al 20%, estos seran usados para Validacion
df_casasCamp20p = df_casasFULL.loc[334:418,['titulo','precio','mets']]

In [8]:
cC80precio = pd.DataFrame(df_casasCamp80p['precio'])
cC80metros = pd.DataFrame(df_casasCamp80p['mets'])

In [9]:
model = linear_model.LinearRegression()

In [10]:
#Se realiza el entrenamiento con una muestra del 80%
model.fit(cC80metros,cC80precio)

LinearRegression()

In [11]:
model.predict(pd.DataFrame([630]))

array([[16921971.49731663]])

In [12]:
cC20precio = pd.DataFrame(df_casasCamp20p['precio'])
cC20metros = pd.DataFrame(df_casasCamp20p['mets'])

In [13]:
#Se realiza la validacion con una muestra del 20%
model.fit(cC20metros,cC20precio)

LinearRegression()

In [14]:
model.predict(pd.DataFrame([630]))

array([[20492609.76138438]])

In [15]:
# Otro resultado utilizando "train_test_split" ----------------------------------------------------------------------------
y= df_casasFULL['precio']
x= df_casasFULL['mets']
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=42)

In [16]:
model2 = linear_model.LinearRegression()

In [17]:
X_train = X_train.values.reshape([X_train.values.shape[0],1])
X_test = X_test.values.reshape([X_test.values.shape[0],1])

In [18]:
model2.fit(X_train,y_train)

LinearRegression()

In [19]:
model2.predict(pd.DataFrame([630]))

array([17638643.02104653])