In [1]:
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
df_depasFULL = pd.read_csv(r'csvRS/departamentos-pro.csv')

In [3]:
#Se limpian los valores de precio y mets y se convierte a flotantes
df_depasFULL['precio'] = df_depasFULL['precio'].replace('[^\d.]', '', regex=True).astype(float)
df_depasFULL['mets'] = df_depasFULL['mets'].replace('[^\d.]', '', regex=True).astype(float)

In [4]:
df_depasFULL = df_depasFULL[df_depasFULL['web-scraper-start-url'].str.contains("campanario", na=False, case=False)]
df_depasFULL.reset_index(drop=True, inplace=True)

In [5]:
df_depasFULL.loc[:,['titulo','precio','mets']]

titulo   precio   mets
0    RENTA DE DEPARTAMENTO EN EL CAMPANARIO 3 RECÁM...  19500.0   96.0
1       Renta departamento amueblado Adamant Queretaro  19000.0   76.0
2       DEPARTAMENTO NUEVO EN LA RESERVA EL CAMPANARIO  15000.0  113.0
3      Renta Departamento Adamant Queretaro  Amueblado  19000.0   75.0
4            DEPARTAMENTO NUEVO AMUEBLADO EN CITY VIEW  24000.0  133.0
..                                                 ...      ...    ...
172  Campanario, Departamento en Noveno Piso en Ren...  18000.0   57.0
173  Departamento Sin Amueblar El Campanario de 120...  29000.0  120.0
174               Renta Departamento Amueblado Adamant  17000.0   56.0
175       Departamento - Fraccionamiento El Campanario  22000.0  234.0
176  Departamento en Renta - El Campanario, Elite -...  22000.0  123.0

[177 rows x 3 columns]

In [6]:
#Se obtienen 141 departamentos los cuales corresponden al 80%, estos seran usados para Entrenamiento
df_depasCamp80p = df_depasFULL.loc[0:140,['titulo','precio','mets']]

In [7]:
#Se obtienen 36 departamentos los cuales corresponden al 20%, estos seran usados para Validacion
df_depasCamp20p = df_depasFULL.loc[141:177,['titulo','precio','mets']]

In [8]:
cC80precio = pd.DataFrame(df_depasCamp80p['precio'])
cC80metros = pd.DataFrame(df_depasCamp80p['mets'])

In [9]:
model = linear_model.LinearRegression()

In [10]:
#Se realiza el entrenamiento con una muestra del 80%
model.fit(cC80metros,cC80precio)

LinearRegression()

In [11]:
model.predict(pd.DataFrame([96]))

array([[20838.73915956]])

In [12]:
cC20precio = pd.DataFrame(df_depasCamp20p['precio'])
cC20metros = pd.DataFrame(df_depasCamp20p['mets'])

In [13]:
#Se realiza la validacion con una muestra del 20%
model.fit(cC20metros,cC20precio)

LinearRegression()

In [14]:
model.predict(pd.DataFrame([96]))

array([[20304.42271115]])

In [15]:
# Otro resultado utilizando "train_test_split"----------------------------------------------------------------------------
y= df_depasFULL['precio']
x= df_depasFULL['mets']
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [16]:
model2 = linear_model.LinearRegression()

In [17]:
X_train = X_train.values.reshape([X_train.values.shape[0],1])
X_test = X_test.values.reshape([X_test.values.shape[0],1])

In [18]:
model2.fit(X_train,y_train)

LinearRegression()

In [19]:
model2.predict(pd.DataFrame([96]))

array([20995.07316409])